meta_name: "Joe Roberts | Full Stack Developer"
meta_title: "Joe Roberts | Full Stack Developer"
meta_description: "Full stack developer | Ruby on Rails | React | Next.js | Typescript | JavaScript| Seeking new opportunities in Montreal, Toronto and beyond."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
