meta_name: "Joe Roberts || Full Stack Developer"
meta_title: "Full Stack Developer based in Montreal"
meta_description: "Full stack developer and ruby on rails bootcamp graduate seeking new opportunities in Montreal, Toronto and beyond."
meta_image: "cover.png" # should exist in `app/assets/images/`
